#!/usr/bin/env python3
"""BUDGET A: fix flagged cutouts (over-removal + background-bleed) using
the plain-bg-regen + chroma-key/flood-fill method. Sole controller of
RunPod spend for this pot — checks the LIVE account balance before every
generation call and stops at a $9 spend (from the recorded baseline),
leaving a $1 safety margin of the $10 pot. Balance-delta is the source of
truth, not call-counting.

Resumable: skips any queued character whose board.png was already
regenerated by this script (tracked in budget_a_log.json).
"""
import json
import sys
import time
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _run_full_roster import prep_input, call_pro, UA  # noqa: E402
from _clean_cutout import clean_cutout  # noqa: E402
from _runpod_balance import get_balance  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[1]
QUEUE_PATH = REPO_ROOT / "cast" / "_rnd_img2img" / "budget_a_queue.json"
LOG_PATH = REPO_ROOT / "cast" / "_rnd_img2img" / "budget_a_log.json"
MANIFEST_PATH = REPO_ROOT / "cast_manifest.json"
REPORT_PATH = REPO_ROOT / "cast" / "_renders_cache" / "_resolve_report.json"
STYLE = "one_piece"
POT_CAP = 9.0  # stop at $9 spent of the $10 pot

PROMPT_TEMPLATE = (
    "Restyle this World of Warcraft character transmog render into clean "
    "bold-ink anime art in the style of One Piece: bold black linework, "
    "flat cel shading, vibrant saturated colors. This character is a "
    "{race} {klass}. Preserve the character's exact armor, weapons, "
    "colors, and gear details from the reference image precisely, do not "
    "invent new equipment. Dynamic action pose, full character visible "
    "head to toe, portrait framing, 3:4 aspect ratio. IMPORTANT: keep the "
    "background a plain solid flat chroma-key MAGENTA/hot-pink backdrop "
    "(like a studio screen, hex FF00FF) — do NOT add any scene, building, "
    "floor, or shadow. No environment at all, just the character on flat "
    "solid magenta, like a character-select portrait."
)
# Green collides with orc/goblin/draenei skin and fel/nature effects;
# magenta essentially never appears in WoW character palettes.


def load_log():
    if LOG_PATH.exists():
        return json.loads(LOG_PATH.read_text(encoding="utf-8"))
    return {"fixed": [], "failed": [], "spend_checkpoints": []}


def save_log(log):
    LOG_PATH.write_text(json.dumps(log, indent=2), encoding="utf-8")


def update_manifest(key):
    for attempt in range(6):
        m = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
        node = m.setdefault("characters", {}).setdefault(key, {})
        styles = node.setdefault("styles", {})
        prev = styles.get(STYLE) or {}
        styles[STYLE] = dict(
            prev,
            cutout_method="plain_bg_regen+chroma_key_flood_fill",
            version=(prev.get("version") or 1) + 1,
            generated_at=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        )
        MANIFEST_PATH.write_text(json.dumps(m, indent=2, ensure_ascii=False), encoding="utf-8")
        time.sleep(0.3)
        check = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
        if check.get("characters", {}).get(key, {}).get("styles", {}).get(STYLE, {}).get("cutout_method"):
            return True
    return False


def main():
    baseline = get_balance()
    print(f"[budget-a] baseline balance ${baseline:.4f}  cap: stop at ${POT_CAP:.2f} spent", flush=True)

    queue = json.loads(QUEUE_PATH.read_text(encoding="utf-8"))
    report = json.loads(REPORT_PATH.read_text(encoding="utf-8"))
    by_key = {e["entry"]: e for e in report["resolved"]}

    log = load_log()
    done_set = set(log["fixed"])

    for i, key in enumerate(queue):
        if key in done_set:
            print(f"[{i+1}/{len(queue)}] skip  {key} (already fixed)", flush=True)
            continue

        balance = get_balance()
        spent = baseline - balance
        if spent >= POT_CAP:
            print(f"[stop] Budget A spent ${spent:.4f} >= ${POT_CAP:.2f} cap. Stopping.", flush=True)
            remaining = [k for k in queue[i:] if k not in done_set]
            print(f"[stop] {len(remaining)} characters not fixed: {remaining}", flush=True)
            break

        entry = by_key.get(key)
        if not entry:
            print(f"[{i+1}/{len(queue)}] FAIL  {key} (not in resolve report)", flush=True)
            log["failed"].append(key)
            save_log(log)
            continue

        char_dir = REPO_ROOT / "cast" / key / STYLE
        plainbg_path = char_dir / "_plainbg_source.png"
        board_path = char_dir / "board.png"

        try:
            render_path = Path(entry["out_path"])
            cropped = prep_input(render_path)
            prompt = PROMPT_TEMPLATE.format(race=entry.get("race") or "", klass=entry.get("class") or "adventurer")
            url, cost, req_id = call_pro(prompt, cropped)
            req = urllib.request.Request(url, headers=UA)
            with urllib.request.urlopen(req, timeout=60) as resp:
                char_dir.mkdir(parents=True, exist_ok=True)
                plainbg_path.write_bytes(resp.read())

            from PIL import Image
            im = Image.open(plainbg_path).convert("RGB")
            bg_color = im.getpixel((5, 5))
            retained, total = clean_cutout(plainbg_path, board_path, bg_color=bg_color, tol=45, small_hole_frac=0.02)
            ratio = retained / total if total else 1.0

            update_manifest(key)
            log["fixed"].append(key)
            done_set.add(key)

            new_balance = get_balance()
            spent_now = baseline - new_balance
            log["spend_checkpoints"].append({"key": key, "balance": new_balance, "spent_from_baseline": round(spent_now, 4)})
            save_log(log)
            print(f"[{i+1}/{len(queue)}] fixed {key}  cutout_ratio={ratio:.1%}  "
                  f"balance=${new_balance:.4f}  spent=${spent_now:.4f}/{POT_CAP:.2f}", flush=True)
        except Exception as e:
            log["failed"].append(key)
            save_log(log)
            print(f"[{i+1}/{len(queue)}] FAIL  {key}  ({e})", flush=True)

        time.sleep(0.2)

    final_balance = get_balance()
    print(f"\n[done] Budget A actual spend: ${baseline - final_balance:.4f} "
          f"(baseline ${baseline:.4f} -> ${final_balance:.4f})", flush=True)
    print(f"[done] fixed={len(log['fixed'])} failed={len(log['failed'])}", flush=True)


if __name__ == "__main__":
    main()
